from fpdf import FPDF
import datetime

def create_pdf(text):

    pdf = FPDF()

    pdf.add_page()

    pdf.set_font("Arial", size=16)

    pdf.cell(200, 10, txt="AI Research Certificate", ln=True)

    pdf.set_font("Arial", size=12)

    pdf.cell(200, 10, txt="Generated by Fantastic WEB4 AI", ln=True)

    pdf.cell(200, 10, txt=str(datetime.datetime.now()), ln=True)

    pdf.ln(10)

    for line in text.split("\n"):

        pdf.cell(200, 8, txt=line, ln=True)

    return pdf.output(dest="S").encode("latin-1")